inertial_frame_id: world
waypoints:
  -
    point: [12, -130, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [42, -130, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [42, -145, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [12, -145, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [12, -160, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [42, -160, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [42, -175, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [12, -175, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [12, -190, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [42, -190, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [42, -205, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [12, -205, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [12, -220, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [42, -220, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [42, -235, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [12, -235, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [12, -250, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [42, -250, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [42, -265, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [12, -265, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [12, -280, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [42, -280, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [42, -295, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [12, -295, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [12, -310, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [42, -310, -80]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False